"""
高质量离线数据集 — 覆盖 Foundry 常见搜索场景
===================================================

场景：
  • 文本分析 / NLP            (python)
  • HTTP 客户端 / 网络请求     (python, node, go)
  • 图像 处理 / 计算机视觉     (python)
  • CLI 框架 / 参数解析       (python, node)
  • 数据库 ORM / 驱动         (python, go)
  • 数据可视化 / 图表         (python, js)
  • 日志 / 监控               (python, go)
  • 机器学习 通用框架          (python)
  • 测试框架                  (python, js)
  • 加解密 / 安全             (python)

说明：
  数据基于公开 GitHub 元数据构造（stars / pushed_at 等已做近似，不是实时值）。
  字段齐全，足以覆盖 评分引擎 + 风险分析 的全部代码路径。
"""

from __future__ import annotations

from typing import Final


# ═══════════════════════════════════════════════════════════════════
#  1) MOCK_REPOS — search() 返回的候选摘要
# ═══════════════════════════════════════════════════════════════════

MOCK_REPOS: Final[list[dict]] = [
    # ── 文本分析 / NLP ─────────────────────────────────────────
    {
        "full_name": "sloria/TextBlob",
        "url": "https://github.com/sloria/TextBlob",
        "description": "Simple, Pythonic text processing: sentiment, POS tagging, noun phrase extraction, translation, and more.",
        "stars": 8920,
        "language": "Python",
        "topics": ["nlp", "sentiment-analysis", "text-processing", "python"],
    },
    {
        "full_name": "cltl/python-for-text-analysis",
        "url": "https://github.com/cltl/python-for-text-analysis",
        "description": "Repository for the Python for Text Analysis course taught at Vrije Universiteit Amsterdam.",
        "stars": 840,
        "language": "Python",
        "topics": ["text-analysis", "education", "tutorial", "nlp"],
    },
    {
        "full_name": "explosion/spaCy",
        "url": "https://github.com/explosion/spaCy",
        "description": "Industrial-strength Natural Language Processing (NLP) in Python.",
        "stars": 28500,
        "language": "Python",
        "topics": ["nlp", "machine-learning", "natural-language-processing", "python", "ai"],
    },
    {
        "full_name": "nltk/nltk",
        "url": "https://github.com/nltk/nltk",
        "description": "Natural Language Toolkit — suite of libraries and programs for symbolic and statistical natural language processing.",
        "stars": 12800,
        "language": "Python",
        "topics": ["nlp", "text-processing", "python", "machine-learning"],
    },
    {
        "full_name": "allenai/allennlp",
        "url": "https://github.com/allenai/allennlp",
        "description": "An open-source NLP research library, built on PyTorch. (ARCHIVED — no longer maintained)",
        "stars": 11500,
        "language": "Python",
        "topics": ["nlp", "pytorch", "machine-learning"],
    },

    # ── HTTP 客户端 ────────────────────────────────────────────
    {
        "full_name": "psf/requests",
        "url": "https://github.com/psf/requests",
        "description": "A simple, yet elegant, HTTP library.",
        "stars": 51500,
        "language": "Python",
        "topics": ["http", "http-client", "python", "requests"],
    },
    {
        "full_name": "encode/httpx",
        "url": "https://github.com/encode/httpx",
        "description": "A next generation HTTP client for Python — async/await, HTTP/2, fully type annotated.",
        "stars": 12400,
        "language": "Python",
        "topics": ["http", "async", "python", "http-client"],
    },
    {
        "full_name": "aio-libs/aiohttp",
        "url": "https://github.com/aio-libs/aiohttp",
        "description": "Asynchronous HTTP client/server framework for asyncio and Python.",
        "stars": 14500,
        "language": "Python",
        "topics": ["async", "http", "aiohttp", "asyncio", "http-client", "http-server"],
    },
    {
        "full_name": "axios/axios",
        "url": "https://github.com/axios/axios",
        "description": "Promise based HTTP client for the browser and node.js.",
        "stars": 104000,
        "language": "JavaScript",
        "topics": ["http", "http-client", "javascript", "nodejs"],
    },

    # ── 图像 / 计算机视觉 ───────────────────────────────────────
    {
        "full_name": "python-pillow/Pillow",
        "url": "https://github.com/python-pillow/Pillow",
        "description": "Python Imaging Library (Fork) — the friendly PIL fork.",
        "stars": 11900,
        "language": "Python",
        "topics": ["image-processing", "python", "pil", "graphics"],
    },
    {
        "full_name": "opencv/opencv-python",
        "url": "https://github.com/opencv/opencv-python",
        "description": "Automated CI toolchain to produce pre-compiled OpenCV packages for Python.",
        "stars": 4100,
        "language": "Python",
        "topics": ["opencv", "computer-vision", "python"],
    },
    {
        "full_name": "ultralytics/ultralytics",
        "url": "https://github.com/ultralytics/ultralytics",
        "description": "YOLOv8 / YOLOv10 — the latest version of the world's most popular computer vision models.",
        "stars": 31000,
        "language": "Python",
        "topics": ["computer-vision", "yolo", "deep-learning", "object-detection"],
    },

    # ── CLI 框架 ──────────────────────────────────────────────
    {
        "full_name": "pallets/click",
        "url": "https://github.com/pallets/click",
        "description": "Python composable command line interface toolkit.",
        "stars": 14900,
        "language": "Python",
        "topics": ["cli", "python", "command-line"],
    },
    {
        "full_name": "tiangolo/typer",
        "url": "https://github.com/tiangolo/typer",
        "description": "Typer, build great CLIs. Easy to code. Based on Python type hints.",
        "stars": 14500,
        "language": "Python",
        "topics": ["cli", "python", "typer", "type-hints"],
    },
    {
        "full_name": "google/python-fire",
        "url": "https://github.com/google/python-fire",
        "description": "Python Fire is a library for automatically generating CLIs from absolutely any Python object.",
        "stars": 26200,
        "language": "Python",
        "topics": ["cli", "python", "command-line"],
    },

    # ── 数据库 ORM / 驱动 ─────────────────────────────────────
    {
        "full_name": "sqlalchemy/sqlalchemy",
        "url": "https://github.com/sqlalchemy/sqlalchemy",
        "description": "The Database Toolkit for Python.",
        "stars": 10200,
        "language": "Python",
        "topics": ["orm", "sql", "database", "python"],
    },
    {
        "full_name": "encode/databases",
        "url": "https://github.com/encode/databases",
        "description": "Async database support for Python. async SQLAlchemy core queries, postgres, mysql, sqlite.",
        "stars": 3700,
        "language": "Python",
        "topics": ["database", "async", "postgres", "mysql", "sqlite"],
    },
    {
        "full_name": "redis/redis-py",
        "url": "https://github.com/redis/redis-py",
        "description": "Redis Python Client.",
        "stars": 12500,
        "language": "Python",
        "topics": ["redis", "python", "cache", "database"],
    },

    # ── 数据可视化 ────────────────────────────────────────────
    {
        "full_name": "matplotlib/matplotlib",
        "url": "https://github.com/matplotlib/matplotlib",
        "description": "matplotlib: plotting with Python.",
        "stars": 19200,
        "language": "Python",
        "topics": ["plotting", "visualization", "python", "charts"],
    },
    {
        "full_name": "plotly/plotly.py",
        "url": "https://github.com/plotly/plotly.py",
        "description": "The interactive graphing library for Python. 40+ chart types.",
        "stars": 15200,
        "language": "Python",
        "topics": ["plotly", "visualization", "charts", "data-visualization"],
    },
    {
        "full_name": "mwaskom/seaborn",
        "url": "https://github.com/mwaskom/seaborn",
        "description": "Statistical data visualization in Python, built on matplotlib.",
        "stars": 12400,
        "language": "Python",
        "topics": ["visualization", "statistics", "charts", "python"],
    },

    # ── 日志 / 监控 ───────────────────────────────────────────
    {
        "full_name": "Delgan/loguru",
        "url": "https://github.com/Delgan/loguru",
        "description": "Python logging made (stupidly) simple.",
        "stars": 17100,
        "language": "Python",
        "topics": ["logging", "python", "logger"],
    },
    {
        "full_name": "structlog/structlog",
        "url": "https://github.com/structlog/structlog",
        "description": "Structured Logging for Python. Add structure to your log entries.",
        "stars": 3200,
        "language": "Python",
        "topics": ["logging", "structured-logging", "python"],
    },

    # ── ML 框架 ───────────────────────────────────────────────
    {
        "full_name": "pytorch/pytorch",
        "url": "https://github.com/pytorch/pytorch",
        "description": "Tensors and Dynamic neural networks in Python with strong GPU acceleration.",
        "stars": 82000,
        "language": "Python",
        "topics": ["deep-learning", "machine-learning", "pytorch", "gpu", "ai"],
    },
    {
        "full_name": "tensorflow/tensorflow",
        "url": "https://github.com/tensorflow/tensorflow",
        "description": "An end-to-end open source platform for machine learning.",
        "stars": 184000,
        "language": "C++",
        "topics": ["deep-learning", "machine-learning", "tensorflow", "ai"],
    },
    {
        "full_name": "scikit-learn/scikit-learn",
        "url": "https://github.com/scikit-learn/scikit-learn",
        "description": "scikit-learn: machine learning in Python.",
        "stars": 58000,
        "language": "Python",
        "topics": ["machine-learning", "data-science", "python", "statistics"],
    },

    # ── 测试框架 ──────────────────────────────────────────────
    {
        "full_name": "pytest-dev/pytest",
        "url": "https://github.com/pytest-dev/pytest",
        "description": "The pytest framework makes it easy to write small tests, yet scales to support complex functional testing.",
        "stars": 11800,
        "language": "Python",
        "topics": ["testing", "python", "unit-testing"],
    },
    {
        "full_name": "jestjs/jest",
        "url": "https://github.com/jestjs/jest",
        "description": "Delightful JavaScript Testing.",
        "stars": 44000,
        "language": "TypeScript",
        "topics": ["testing", "javascript", "unit-testing"],
    },

    # ── 加解密 / 安全 ──────────────────────────────────────────
    {
        "full_name": "pyca/cryptography",
        "url": "https://github.com/pyca/cryptography",
        "description": "cryptography is a package which provides cryptographic recipes and primitives to Python developers.",
        "stars": 6600,
        "language": "Python",
        "topics": ["cryptography", "security", "python", "encryption"],
    },
    {
        "full_name": "Legrandin/pycryptodome",
        "url": "https://github.com/Legrandin/pycryptodome",
        "description": "A self-contained Python package of low-level cryptographic primitives. (PyCrypto successor)",
        "stars": 2500,
        "language": "Python",
        "topics": ["cryptography", "encryption", "python"],
    },
    # 故意放一个 License 不明的组件，用来测试 UNKNOWN_LICENSE 风险
    {
        "full_name": "anon-test/acme-text-utils",
        "url": "https://github.com/anon-test/acme-text-utils",
        "description": "A collection of text utility functions. License file missing.",
        "stars": 320,
        "language": "Python",
        "topics": ["text", "utils"],
    },
    # 故意放一个 STALE 组件（超过 500 天无更新）
    {
        "full_name": "legacy-tools/python-texttool",
        "url": "https://github.com/legacy-tools/python-texttool",
        "description": "An early 2010s text processing library. Last commit 2022.",
        "stars": 890,
        "language": "Python",
        "topics": ["text", "legacy"],
    },
]


# ═══════════════════════════════════════════════════════════════════
#  2) MOCK_EVIDENCE — fetch_evidence() 返回的完整证据
#     覆盖评分引擎 + 风险分析 的全部代码路径
# ═══════════════════════════════════════════════════════════════════

# pushed_at / created_at / last_commit_date 用 ISO 格式字符串，_parse_dt 会解析
def _e(days_ago: int) -> str:
    """N 天前的 UTC ISO 时间。"""
    from datetime import datetime, timedelta, timezone
    dt = datetime.now(timezone.utc) - timedelta(days=days_ago)
    return dt.strftime("%Y-%m-%dT%H:%M:%SZ")


MOCK_EVIDENCE: Final[dict[str, dict]] = {
    # ── 文本分析 ──────────────────────────────────────────────
    "sloria/textblob": {
        "source": "github",
        "full_name": "sloria/TextBlob",
        "url": "https://github.com/sloria/TextBlob",
        "description": "Simple, Pythonic text processing: sentiment, POS tagging, noun phrase extraction, translation.",
        "default_branch": "dev",
        "language": "Python",
        "license_name": "MIT",
        "license_category": "permissive",
        "stars": 8920,
        "forks": 1120,
        "watchers": 230,
        "subscribers": 330,
        "created_at": "2013-08-22T12:00:00Z",
        "pushed_at": _e(25),
        "archived": False,
        "is_fork": False,
        "homepage": "https://textblob.readthedocs.io/",
        "has_wiki": True,
        "has_pages": False,
        "readme_size_bytes": 9400,
        "topics": ["nlp", "sentiment-analysis", "text-processing", "python"],
        "issues": {
            "open_count": 38,
            "closed_count": 430,
            "avg_days_open": 42.0,
            "recent_30d_opened": 6,
            "recent_30d_closed": 9,
            "bug_label_count": 11,
        },
        "pull_requests": {
            "open_count": 5,
            "merged_30d": 4,
            "avg_days_to_merge": 7.2,
        },
        "commits": {
            "last_commit_date": _e(22),
            "commits_30d": 11,
            "commits_90d": 34,
            "contributors_90d": 5,
        },
    },
    "cltl/python-for-text-analysis": {
        "source": "github",
        "full_name": "cltl/python-for-text-analysis",
        "url": "https://github.com/cltl/python-for-text-analysis",
        "description": "Repository for the Python for Text Analysis course taught at Vrije Universiteit Amsterdam.",
        "default_branch": "main",
        "language": "Python",
        "license_name": "GPL-3.0",
        "license_category": "strong_copyleft",
        "stars": 840,
        "forks": 520,
        "watchers": 48,
        "subscribers": 48,
        "created_at": "2018-03-01T10:00:00Z",
        "pushed_at": _e(60),
        "archived": False,
        "is_fork": False,
        "homepage": None,
        "has_wiki": False,
        "has_pages": True,
        "readme_size_bytes": 5200,
        "topics": ["text-analysis", "education", "tutorial", "nlp"],
        "issues": {
            "open_count": 8,
            "closed_count": 22,
            "avg_days_open": 75.0,
            "recent_30d_opened": 1,
            "recent_30d_closed": 0,
            "bug_label_count": 2,
        },
        "pull_requests": {
            "open_count": 1,
            "merged_30d": 0,
            "avg_days_to_merge": 30.0,
        },
        "commits": {
            "last_commit_date": _e(58),
            "commits_30d": 2,
            "commits_90d": 6,
            "contributors_90d": 1,
        },
    },
    "explosion/spacy": {
        "source": "github",
        "full_name": "explosion/spaCy",
        "url": "https://github.com/explosion/spaCy",
        "description": "Industrial-strength Natural Language Processing (NLP) in Python.",
        "default_branch": "main",
        "language": "Python",
        "license_name": "MIT",
        "license_category": "permissive",
        "stars": 28500,
        "forks": 4200,
        "watchers": 980,
        "subscribers": 760,
        "created_at": "2015-02-05T10:00:00Z",
        "pushed_at": _e(2),
        "archived": False,
        "is_fork": False,
        "homepage": "https://spacy.io",
        "has_wiki": False,
        "has_pages": False,
        "readme_size_bytes": 18500,
        "topics": ["nlp", "machine-learning", "natural-language-processing", "python", "ai"],
        "issues": {
            "open_count": 92,
            "closed_count": 4800,
            "avg_days_open": 18.0,
            "recent_30d_opened": 34,
            "recent_30d_closed": 58,
            "bug_label_count": 28,
        },
        "pull_requests": {
            "open_count": 14,
            "merged_30d": 42,
            "avg_days_to_merge": 3.5,
        },
        "commits": {
            "last_commit_date": _e(1),
            "commits_30d": 160,
            "commits_90d": 490,
            "contributors_90d": 38,
        },
    },
    "nltk/nltk": {
        "source": "github",
        "full_name": "nltk/nltk",
        "url": "https://github.com/nltk/nltk",
        "description": "Natural Language Toolkit — suite of libraries and programs for symbolic and statistical natural language processing.",
        "default_branch": "develop",
        "language": "Python",
        "license_name": "Apache-2.0",
        "license_category": "permissive",
        "stars": 12800,
        "forks": 2900,
        "watchers": 520,
        "subscribers": 490,
        "created_at": "2011-12-13T10:00:00Z",
        "pushed_at": _e(14),
        "archived": False,
        "is_fork": False,
        "homepage": "https://www.nltk.org/",
        "has_wiki": True,
        "has_pages": True,
        "readme_size_bytes": 12800,
        "topics": ["nlp", "text-processing", "python", "machine-learning"],
        "issues": {
            "open_count": 240,
            "closed_count": 2000,
            "avg_days_open": 115.0,
            "recent_30d_opened": 12,
            "recent_30d_closed": 18,
            "bug_label_count": 68,
        },
        "pull_requests": {
            "open_count": 22,
            "merged_30d": 8,
            "avg_days_to_merge": 28.0,
        },
        "commits": {
            "last_commit_date": _e(12),
            "commits_30d": 22,
            "commits_90d": 76,
            "contributors_90d": 12,
        },
    },
    "allenai/allennlp": {
        "source": "github",
        "full_name": "allenai/allennlp",
        "url": "https://github.com/allenai/allennlp",
        "description": "An open-source NLP research library, built on PyTorch. (ARCHIVED — no longer maintained)",
        "default_branch": "main",
        "language": "Python",
        "license_name": "Apache-2.0",
        "license_category": "permissive",
        "stars": 11500,
        "forks": 1450,
        "watchers": 420,
        "subscribers": 250,
        "created_at": "2017-12-01T10:00:00Z",
        "pushed_at": _e(780),
        "archived": True,
        "is_fork": False,
        "homepage": None,
        "has_wiki": False,
        "has_pages": False,
        "readme_size_bytes": 9800,
        "topics": ["nlp", "pytorch", "machine-learning"],
        "issues": {
            "open_count": 680,
            "closed_count": 2100,
            "avg_days_open": 600.0,
            "recent_30d_opened": 0,
            "recent_30d_closed": 0,
            "bug_label_count": 180,
        },
        "pull_requests": {
            "open_count": 34,
            "merged_30d": 0,
            "avg_days_to_merge": 0.0,
        },
        "commits": {
            "last_commit_date": _e(780),
            "commits_30d": 0,
            "commits_90d": 0,
            "contributors_90d": 0,
        },
    },

    # ── HTTP 客户端 ────────────────────────────────────────────
    "psf/requests": {
        "source": "github",
        "full_name": "psf/requests",
        "url": "https://github.com/psf/requests",
        "description": "A simple, yet elegant, HTTP library.",
        "default_branch": "main",
        "language": "Python",
        "license_name": "Apache-2.0",
        "license_category": "permissive",
        "stars": 51500,
        "forks": 8800,
        "watchers": 1500,
        "subscribers": 1800,
        "created_at": "2011-02-14T10:00:00Z",
        "pushed_at": _e(10),
        "archived": False,
        "is_fork": False,
        "homepage": "https://requests.readthedocs.io/",
        "has_wiki": False,
        "has_pages": False,
        "readme_size_bytes": 14000,
        "topics": ["http", "http-client", "python", "requests"],
        "issues": {
            "open_count": 160,
            "closed_count": 6500,
            "avg_days_open": 28.0,
            "recent_30d_opened": 24,
            "recent_30d_closed": 38,
            "bug_label_count": 42,
        },
        "pull_requests": {
            "open_count": 10,
            "merged_30d": 14,
            "avg_days_to_merge": 5.2,
        },
        "commits": {
            "last_commit_date": _e(8),
            "commits_30d": 28,
            "commits_90d": 82,
            "contributors_90d": 14,
        },
    },
    "encode/httpx": {
        "source": "github",
        "full_name": "encode/httpx",
        "url": "https://github.com/encode/httpx",
        "description": "A next generation HTTP client for Python — async/await, HTTP/2, fully type annotated.",
        "default_branch": "master",
        "language": "Python",
        "license_name": "BSD-3-Clause",
        "license_category": "permissive",
        "stars": 12400,
        "forks": 880,
        "watchers": 210,
        "subscribers": 260,
        "created_at": "2019-04-18T10:00:00Z",
        "pushed_at": _e(4),
        "archived": False,
        "is_fork": False,
        "homepage": "https://www.python-httpx.org/",
        "has_wiki": False,
        "has_pages": False,
        "readme_size_bytes": 16200,
        "topics": ["http", "async", "python", "http-client"],
        "issues": {
            "open_count": 42,
            "closed_count": 1400,
            "avg_days_open": 12.0,
            "recent_30d_opened": 18,
            "recent_30d_closed": 26,
            "bug_label_count": 14,
        },
        "pull_requests": {
            "open_count": 6,
            "merged_30d": 22,
            "avg_days_to_merge": 2.8,
        },
        "commits": {
            "last_commit_date": _e(2),
            "commits_30d": 74,
            "commits_90d": 220,
            "contributors_90d": 18,
        },
    },
    "aio-libs/aiohttp": {
        "source": "github",
        "full_name": "aio-libs/aiohttp",
        "url": "https://github.com/aio-libs/aiohttp",
        "description": "Asynchronous HTTP client/server framework for asyncio and Python.",
        "default_branch": "master",
        "language": "Python",
        "license_name": "Apache-2.0",
        "license_category": "permissive",
        "stars": 14500,
        "forks": 1900,
        "watchers": 320,
        "subscribers": 380,
        "created_at": "2013-10-11T10:00:00Z",
        "pushed_at": _e(6),
        "archived": False,
        "is_fork": False,
        "homepage": "https://docs.aiohttp.org/",
        "has_wiki": False,
        "has_pages": False,
        "readme_size_bytes": 13500,
        "topics": ["async", "http", "aiohttp", "asyncio", "http-client", "http-server"],
        "issues": {
            "open_count": 260,
            "closed_count": 5200,
            "avg_days_open": 46.0,
            "recent_30d_opened": 28,
            "recent_30d_closed": 20,
            "bug_label_count": 72,
        },
        "pull_requests": {
            "open_count": 18,
            "merged_30d": 18,
            "avg_days_to_merge": 7.5,
        },
        "commits": {
            "last_commit_date": _e(5),
            "commits_30d": 48,
            "commits_90d": 160,
            "contributors_90d": 16,
        },
    },
    "axios/axios": {
        "source": "github",
        "full_name": "axios/axios",
        "url": "https://github.com/axios/axios",
        "description": "Promise based HTTP client for the browser and node.js.",
        "default_branch": "v1.x",
        "language": "JavaScript",
        "license_name": "MIT",
        "license_category": "permissive",
        "stars": 104000,
        "forks": 10800,
        "watchers": 2100,
        "subscribers": 2500,
        "created_at": "2014-08-29T10:00:00Z",
        "pushed_at": _e(15),
        "archived": False,
        "is_fork": False,
        "homepage": "https://axios-http.com",
        "has_wiki": False,
        "has_pages": True,
        "readme_size_bytes": 17800,
        "topics": ["http", "http-client", "javascript", "nodejs"],
        "issues": {
            "open_count": 420,
            "closed_count": 9800,
            "avg_days_open": 72.0,
            "recent_30d_opened": 60,
            "recent_30d_closed": 52,
            "bug_label_count": 130,
        },
        "pull_requests": {
            "open_count": 22,
            "merged_30d": 28,
            "avg_days_to_merge": 9.6,
        },
        "commits": {
            "last_commit_date": _e(14),
            "commits_30d": 66,
            "commits_90d": 198,
            "contributors_90d": 22,
        },
    },

    # ── 图像 / CV ─────────────────────────────────────────────
    "python-pillow/pillow": {
        "source": "github",
        "full_name": "python-pillow/Pillow",
        "url": "https://github.com/python-pillow/Pillow",
        "description": "Python Imaging Library (Fork) — the friendly PIL fork.",
        "default_branch": "main",
        "language": "Python",
        "license_name": "MIT",
        "license_category": "permissive",
        "stars": 11900,
        "forks": 2200,
        "watchers": 320,
        "subscribers": 380,
        "created_at": "2013-03-28T10:00:00Z",
        "pushed_at": _e(8),
        "archived": False,
        "is_fork": False,
        "homepage": "https://python-pillow.org",
        "has_wiki": False,
        "has_pages": False,
        "readme_size_bytes": 14000,
        "topics": ["image-processing", "python", "pil", "graphics"],
        "issues": {
            "open_count": 92,
            "closed_count": 5200,
            "avg_days_open": 22.0,
            "recent_30d_opened": 20,
            "recent_30d_closed": 28,
            "bug_label_count": 24,
        },
        "pull_requests": {
            "open_count": 8,
            "merged_30d": 24,
            "avg_days_to_merge": 4.8,
        },
        "commits": {
            "last_commit_date": _e(7),
            "commits_30d": 56,
            "commits_90d": 180,
            "contributors_90d": 20,
        },
    },
    "opencv/opencv-python": {
        "source": "github",
        "full_name": "opencv/opencv-python",
        "url": "https://github.com/opencv/opencv-python",
        "description": "Automated CI toolchain to produce pre-compiled OpenCV packages for Python.",
        "default_branch": "main",
        "language": "Python",
        "license_name": "MIT",
        "license_category": "permissive",
        "stars": 4100,
        "forks": 700,
        "watchers": 90,
        "subscribers": 110,
        "created_at": "2016-08-15T10:00:00Z",
        "pushed_at": _e(20),
        "archived": False,
        "is_fork": False,
        "homepage": None,
        "has_wiki": False,
        "has_pages": False,
        "readme_size_bytes": 7800,
        "topics": ["opencv", "computer-vision", "python"],
        "issues": {
            "open_count": 72,
            "closed_count": 800,
            "avg_days_open": 58.0,
            "recent_30d_opened": 8,
            "recent_30d_closed": 5,
            "bug_label_count": 20,
        },
        "pull_requests": {
            "open_count": 3,
            "merged_30d": 4,
            "avg_days_to_merge": 12.0,
        },
        "commits": {
            "last_commit_date": _e(18),
            "commits_30d": 12,
            "commits_90d": 38,
            "contributors_90d": 3,
        },
    },
    "ultralytics/ultralytics": {
        "source": "github",
        "full_name": "ultralytics/ultralytics",
        "url": "https://github.com/ultralytics/ultralytics",
        "description": "YOLOv8 / YOLOv10 — the latest version of the world's most popular computer vision models.",
        "default_branch": "main",
        "language": "Python",
        "license_name": "AGPL-3.0",
        "license_category": "strong_copyleft",
        "stars": 31000,
        "forks": 6200,
        "watchers": 580,
        "subscribers": 700,
        "created_at": "2023-01-10T10:00:00Z",
        "pushed_at": _e(1),
        "archived": False,
        "is_fork": False,
        "homepage": "https://ultralytics.com",
        "has_wiki": True,
        "has_pages": True,
        "readme_size_bytes": 22000,
        "topics": ["computer-vision", "yolo", "deep-learning", "object-detection"],
        "issues": {
            "open_count": 540,
            "closed_count": 3800,
            "avg_days_open": 14.0,
            "recent_30d_opened": 120,
            "recent_30d_closed": 180,
            "bug_label_count": 120,
        },
        "pull_requests": {
            "open_count": 24,
            "merged_30d": 60,
            "avg_days_to_merge": 2.0,
        },
        "commits": {
            "last_commit_date": _e(0),
            "commits_30d": 320,
            "commits_90d": 950,
            "contributors_90d": 48,
        },
    },

    # ── CLI 框架 ──────────────────────────────────────────────
    "pallets/click": {
        "source": "github",
        "full_name": "pallets/click",
        "url": "https://github.com/pallets/click",
        "description": "Python composable command line interface toolkit.",
        "default_branch": "main",
        "language": "Python",
        "license_name": "BSD-3-Clause",
        "license_category": "permissive",
        "stars": 14900,
        "forks": 1400,
        "watchers": 260,
        "subscribers": 320,
        "created_at": "2014-11-01T10:00:00Z",
        "pushed_at": _e(35),
        "archived": False,
        "is_fork": False,
        "homepage": "https://click.palletsprojects.com/",
        "has_wiki": False,
        "has_pages": False,
        "readme_size_bytes": 11500,
        "topics": ["cli", "python", "command-line"],
        "issues": {
            "open_count": 68,
            "closed_count": 2100,
            "avg_days_open": 35.0,
            "recent_30d_opened": 6,
            "recent_30d_closed": 10,
            "bug_label_count": 18,
        },
        "pull_requests": {
            "open_count": 4,
            "merged_30d": 3,
            "avg_days_to_merge": 12.0,
        },
        "commits": {
            "last_commit_date": _e(32),
            "commits_30d": 6,
            "commits_90d": 22,
            "contributors_90d": 4,
        },
    },
    "tiangolo/typer": {
        "source": "github",
        "full_name": "tiangolo/typer",
        "url": "https://github.com/tiangolo/typer",
        "description": "Typer, build great CLIs. Easy to code. Based on Python type hints.",
        "default_branch": "main",
        "language": "Python",
        "license_name": "MIT",
        "license_category": "permissive",
        "stars": 14500,
        "forks": 640,
        "watchers": 220,
        "subscribers": 260,
        "created_at": "2019-11-26T10:00:00Z",
        "pushed_at": _e(40),
        "archived": False,
        "is_fork": False,
        "homepage": "https://typer.tiangolo.com",
        "has_wiki": False,
        "has_pages": True,
        "readme_size_bytes": 18200,
        "topics": ["cli", "python", "typer", "type-hints"],
        "issues": {
            "open_count": 220,
            "closed_count": 1100,
            "avg_days_open": 85.0,
            "recent_30d_opened": 10,
            "recent_30d_closed": 4,
            "bug_label_count": 58,
        },
        "pull_requests": {
            "open_count": 14,
            "merged_30d": 3,
            "avg_days_to_merge": 35.0,
        },
        "commits": {
            "last_commit_date": _e(38),
            "commits_30d": 4,
            "commits_90d": 18,
            "contributors_90d": 3,
        },
    },
    "google/python-fire": {
        "source": "github",
        "full_name": "google/python-fire",
        "url": "https://github.com/google/python-fire",
        "description": "Python Fire is a library for automatically generating CLIs from absolutely any Python object.",
        "default_branch": "master",
        "language": "Python",
        "license_name": "Apache-2.0",
        "license_category": "permissive",
        "stars": 26200,
        "forks": 1400,
        "watchers": 600,
        "subscribers": 520,
        "created_at": "2017-03-02T10:00:00Z",
        "pushed_at": _e(180),
        "archived": False,
        "is_fork": False,
        "homepage": None,
        "has_wiki": False,
        "has_pages": False,
        "readme_size_bytes": 10200,
        "topics": ["cli", "python", "command-line"],
        "issues": {
            "open_count": 130,
            "closed_count": 480,
            "avg_days_open": 320.0,
            "recent_30d_opened": 2,
            "recent_30d_closed": 0,
            "bug_label_count": 48,
        },
        "pull_requests": {
            "open_count": 12,
            "merged_30d": 0,
            "avg_days_to_merge": 0.0,
        },
        "commits": {
            "last_commit_date": _e(175),
            "commits_30d": 0,
            "commits_90d": 2,
            "contributors_90d": 1,
        },
    },

    # ── 数据库 / ORM ──────────────────────────────────────────
    "sqlalchemy/sqlalchemy": {
        "source": "github",
        "full_name": "sqlalchemy/sqlalchemy",
        "url": "https://github.com/sqlalchemy/sqlalchemy",
        "description": "The Database Toolkit for Python.",
        "default_branch": "main",
        "language": "Python",
        "license_name": "MIT",
        "license_category": "permissive",
        "stars": 10200,
        "forks": 1900,
        "watchers": 260,
        "subscribers": 340,
        "created_at": "2011-08-18T10:00:00Z",
        "pushed_at": _e(3),
        "archived": False,
        "is_fork": False,
        "homepage": "https://www.sqlalchemy.org/",
        "has_wiki": False,
        "has_pages": False,
        "readme_size_bytes": 16800,
        "topics": ["orm", "sql", "database", "python"],
        "issues": {
            "open_count": 140,
            "closed_count": 8800,
            "avg_days_open": 15.0,
            "recent_30d_opened": 40,
            "recent_30d_closed": 48,
            "bug_label_count": 38,
        },
        "pull_requests": {
            "open_count": 6,
            "merged_30d": 32,
            "avg_days_to_merge": 2.4,
        },
        "commits": {
            "last_commit_date": _e(2),
            "commits_30d": 140,
            "commits_90d": 430,
            "contributors_90d": 18,
        },
    },
    "encode/databases": {
        "source": "github",
        "full_name": "encode/databases",
        "url": "https://github.com/encode/databases",
        "description": "Async database support for Python. async SQLAlchemy core queries.",
        "default_branch": "master",
        "language": "Python",
        "license_name": "BSD-3-Clause",
        "license_category": "permissive",
        "stars": 3700,
        "forks": 340,
        "watchers": 90,
        "subscribers": 90,
        "created_at": "2018-11-01T10:00:00Z",
        "pushed_at": _e(120),
        "archived": False,
        "is_fork": False,
        "homepage": None,
        "has_wiki": False,
        "has_pages": False,
        "readme_size_bytes": 7800,
        "topics": ["database", "async", "postgres", "mysql", "sqlite"],
        "issues": {
            "open_count": 88,
            "closed_count": 520,
            "avg_days_open": 160.0,
            "recent_30d_opened": 2,
            "recent_30d_closed": 1,
            "bug_label_count": 26,
        },
        "pull_requests": {
            "open_count": 10,
            "merged_30d": 0,
            "avg_days_to_merge": 0.0,
        },
        "commits": {
            "last_commit_date": _e(118),
            "commits_30d": 0,
            "commits_90d": 2,
            "contributors_90d": 1,
        },
    },
    "redis/redis-py": {
        "source": "github",
        "full_name": "redis/redis-py",
        "url": "https://github.com/redis/redis-py",
        "description": "Redis Python Client.",
        "default_branch": "master",
        "language": "Python",
        "license_name": "MIT",
        "license_category": "permissive",
        "stars": 12500,
        "forks": 2400,
        "watchers": 260,
        "subscribers": 380,
        "created_at": "2010-06-20T10:00:00Z",
        "pushed_at": _e(18),
        "archived": False,
        "is_fork": False,
        "homepage": "https://redis.readthedocs.io/",
        "has_wiki": False,
        "has_pages": False,
        "readme_size_bytes": 11200,
        "topics": ["redis", "python", "cache", "database"],
        "issues": {
            "open_count": 150,
            "closed_count": 4500,
            "avg_days_open": 35.0,
            "recent_30d_opened": 18,
            "recent_30d_closed": 24,
            "bug_label_count": 42,
        },
        "pull_requests": {
            "open_count": 8,
            "merged_30d": 12,
            "avg_days_to_merge": 6.0,
        },
        "commits": {
            "last_commit_date": _e(15),
            "commits_30d": 34,
            "commits_90d": 98,
            "contributors_90d": 14,
        },
    },

    # ── 可视化 ────────────────────────────────────────────────
    "matplotlib/matplotlib": {
        "source": "github",
        "full_name": "matplotlib/matplotlib",
        "url": "https://github.com/matplotlib/matplotlib",
        "description": "matplotlib: plotting with Python.",
        "default_branch": "main",
        "language": "Python",
        "license_name": "PSF",
        "license_category": "permissive",
        "stars": 19200,
        "forks": 7000,
        "watchers": 520,
        "subscribers": 700,
        "created_at": "2011-02-17T10:00:00Z",
        "pushed_at": _e(4),
        "archived": False,
        "is_fork": False,
        "homepage": "https://matplotlib.org",
        "has_wiki": True,
        "has_pages": True,
        "readme_size_bytes": 18200,
        "topics": ["plotting", "visualization", "python", "charts"],
        "issues": {
            "open_count": 1500,
            "closed_count": 27000,
            "avg_days_open": 140.0,
            "recent_30d_opened": 80,
            "recent_30d_closed": 90,
            "bug_label_count": 480,
        },
        "pull_requests": {
            "open_count": 180,
            "merged_30d": 80,
            "avg_days_to_merge": 18.0,
        },
        "commits": {
            "last_commit_date": _e(3),
            "commits_30d": 260,
            "commits_90d": 820,
            "contributors_90d": 80,
        },
    },
    "plotly/plotly.py": {
        "source": "github",
        "full_name": "plotly/plotly.py",
        "url": "https://github.com/plotly/plotly.py",
        "description": "The interactive graphing library for Python. 40+ chart types.",
        "default_branch": "master",
        "language": "Python",
        "license_name": "MIT",
        "license_category": "permissive",
        "stars": 15200,
        "forks": 2400,
        "watchers": 420,
        "subscribers": 420,
        "created_at": "2013-08-16T10:00:00Z",
        "pushed_at": _e(12),
        "archived": False,
        "is_fork": False,
        "homepage": "https://plotly.com/python/",
        "has_wiki": False,
        "has_pages": False,
        "readme_size_bytes": 16800,
        "topics": ["plotly", "visualization", "charts", "data-visualization"],
        "issues": {
            "open_count": 1200,
            "closed_count": 6200,
            "avg_days_open": 180.0,
            "recent_30d_opened": 40,
            "recent_30d_closed": 30,
            "bug_label_count": 380,
        },
        "pull_requests": {
            "open_count": 22,
            "merged_30d": 18,
            "avg_days_to_merge": 15.0,
        },
        "commits": {
            "last_commit_date": _e(10),
            "commits_30d": 70,
            "commits_90d": 220,
            "contributors_90d": 24,
        },
    },
    "mwaskom/seaborn": {
        "source": "github",
        "full_name": "mwaskom/seaborn",
        "url": "https://github.com/mwaskom/seaborn",
        "description": "Statistical data visualization in Python, built on matplotlib.",
        "default_branch": "main",
        "language": "Python",
        "license_name": "BSD-3-Clause",
        "license_category": "permissive",
        "stars": 12400,
        "forks": 1800,
        "watchers": 320,
        "subscribers": 300,
        "created_at": "2012-12-16T10:00:00Z",
        "pushed_at": _e(55),
        "archived": False,
        "is_fork": False,
        "homepage": "https://seaborn.pydata.org",
        "has_wiki": False,
        "has_pages": False,
        "readme_size_bytes": 12500,
        "topics": ["visualization", "statistics", "charts", "python"],
        "issues": {
            "open_count": 120,
            "closed_count": 2800,
            "avg_days_open": 80.0,
            "recent_30d_opened": 6,
            "recent_30d_closed": 14,
            "bug_label_count": 40,
        },
        "pull_requests": {
            "open_count": 6,
            "merged_30d": 5,
            "avg_days_to_merge": 18.0,
        },
        "commits": {
            "last_commit_date": _e(52),
            "commits_30d": 4,
            "commits_90d": 18,
            "contributors_90d": 3,
        },
    },

    # ── 日志 / 监控 ───────────────────────────────────────────
    "delgan/loguru": {
        "source": "github",
        "full_name": "Delgan/loguru",
        "url": "https://github.com/Delgan/loguru",
        "description": "Python logging made (stupidly) simple.",
        "default_branch": "master",
        "language": "Python",
        "license_name": "MIT",
        "license_category": "permissive",
        "stars": 17100,
        "forks": 640,
        "watchers": 220,
        "subscribers": 260,
        "created_at": "2018-03-16T10:00:00Z",
        "pushed_at": _e(70),
        "archived": False,
        "is_fork": False,
        "homepage": None,
        "has_wiki": False,
        "has_pages": False,
        "readme_size_bytes": 18200,
        "topics": ["logging", "python", "logger"],
        "issues": {
            "open_count": 90,
            "closed_count": 980,
            "avg_days_open": 90.0,
            "recent_30d_opened": 6,
            "recent_30d_closed": 4,
            "bug_label_count": 22,
        },
        "pull_requests": {
            "open_count": 8,
            "merged_30d": 2,
            "avg_days_to_merge": 40.0,
        },
        "commits": {
            "last_commit_date": _e(68),
            "commits_30d": 2,
            "commits_90d": 10,
            "contributors_90d": 2,
        },
    },
    "structlog/structlog": {
        "source": "github",
        "full_name": "structlog/structlog",
        "url": "https://github.com/structlog/structlog",
        "description": "Structured Logging for Python. Add structure to your log entries.",
        "default_branch": "main",
        "language": "Python",
        "license_name": "Apache-2.0",
        "license_category": "permissive",
        "stars": 3200,
        "forks": 300,
        "watchers": 58,
        "subscribers": 62,
        "created_at": "2013-06-26T10:00:00Z",
        "pushed_at": _e(20),
        "archived": False,
        "is_fork": False,
        "homepage": "https://www.structlog.org/",
        "has_wiki": False,
        "has_pages": False,
        "readme_size_bytes": 11200,
        "topics": ["logging", "structured-logging", "python"],
        "issues": {
            "open_count": 22,
            "closed_count": 680,
            "avg_days_open": 22.0,
            "recent_30d_opened": 4,
            "recent_30d_closed": 8,
            "bug_label_count": 6,
        },
        "pull_requests": {
            "open_count": 2,
            "merged_30d": 6,
            "avg_days_to_merge": 5.0,
        },
        "commits": {
            "last_commit_date": _e(18),
            "commits_30d": 12,
            "commits_90d": 40,
            "contributors_90d": 5,
        },
    },

    # ── ML 框架 ───────────────────────────────────────────────
    "pytorch/pytorch": {
        "source": "github",
        "full_name": "pytorch/pytorch",
        "url": "https://github.com/pytorch/pytorch",
        "description": "Tensors and Dynamic neural networks in Python with strong GPU acceleration.",
        "default_branch": "main",
        "language": "Python",
        "license_name": "BSD-3-Clause",
        "license_category": "permissive",
        "stars": 82000,
        "forks": 19000,
        "watchers": 2400,
        "subscribers": 3100,
        "created_at": "2016-08-24T10:00:00Z",
        "pushed_at": _e(0),
        "archived": False,
        "is_fork": False,
        "homepage": "https://pytorch.org",
        "has_wiki": True,
        "has_pages": False,
        "readme_size_bytes": 22000,
        "topics": ["deep-learning", "machine-learning", "pytorch", "gpu", "ai"],
        "issues": {
            "open_count": 7800,
            "closed_count": 82000,
            "avg_days_open": 55.0,
            "recent_30d_opened": 600,
            "recent_30d_closed": 720,
            "bug_label_count": 2400,
        },
        "pull_requests": {
            "open_count": 800,
            "merged_30d": 900,
            "avg_days_to_merge": 4.5,
        },
        "commits": {
            "last_commit_date": _e(0),
            "commits_30d": 4200,
            "commits_90d": 12800,
            "contributors_90d": 680,
        },
    },
    "tensorflow/tensorflow": {
        "source": "github",
        "full_name": "tensorflow/tensorflow",
        "url": "https://github.com/tensorflow/tensorflow",
        "description": "An end-to-end open source platform for machine learning.",
        "default_branch": "master",
        "language": "C++",
        "license_name": "Apache-2.0",
        "license_category": "permissive",
        "stars": 184000,
        "forks": 74000,
        "watchers": 4200,
        "subscribers": 5800,
        "created_at": "2015-11-07T10:00:00Z",
        "pushed_at": _e(1),
        "archived": False,
        "is_fork": False,
        "homepage": "https://www.tensorflow.org",
        "has_wiki": True,
        "has_pages": True,
        "readme_size_bytes": 20000,
        "topics": ["deep-learning", "machine-learning", "tensorflow", "ai"],
        "issues": {
            "open_count": 11000,
            "closed_count": 128000,
            "avg_days_open": 85.0,
            "recent_30d_opened": 500,
            "recent_30d_closed": 480,
            "bug_label_count": 3800,
        },
        "pull_requests": {
            "open_count": 600,
            "merged_30d": 500,
            "avg_days_to_merge": 6.0,
        },
        "commits": {
            "last_commit_date": _e(1),
            "commits_30d": 2800,
            "commits_90d": 9200,
            "contributors_90d": 520,
        },
    },
    "scikit-learn/scikit-learn": {
        "source": "github",
        "full_name": "scikit-learn/scikit-learn",
        "url": "https://github.com/scikit-learn/scikit-learn",
        "description": "scikit-learn: machine learning in Python.",
        "default_branch": "main",
        "language": "Python",
        "license_name": "BSD-3-Clause",
        "license_category": "permissive",
        "stars": 58000,
        "forks": 25000,
        "watchers": 1800,
        "subscribers": 2200,
        "created_at": "2010-09-28T10:00:00Z",
        "pushed_at": _e(5),
        "archived": False,
        "is_fork": False,
        "homepage": "https://scikit-learn.org",
        "has_wiki": False,
        "has_pages": False,
        "readme_size_bytes": 18000,
        "topics": ["machine-learning", "data-science", "python", "statistics"],
        "issues": {
            "open_count": 1600,
            "closed_count": 24000,
            "avg_days_open": 95.0,
            "recent_30d_opened": 60,
            "recent_30d_closed": 80,
            "bug_label_count": 520,
        },
        "pull_requests": {
            "open_count": 200,
            "merged_30d": 90,
            "avg_days_to_merge": 15.0,
        },
        "commits": {
            "last_commit_date": _e(4),
            "commits_30d": 280,
            "commits_90d": 880,
            "contributors_90d": 110,
        },
    },

    # ── 测试框架 ──────────────────────────────────────────────
    "pytest-dev/pytest": {
        "source": "github",
        "full_name": "pytest-dev/pytest",
        "url": "https://github.com/pytest-dev/pytest",
        "description": "The pytest framework makes it easy to write small tests.",
        "default_branch": "main",
        "language": "Python",
        "license_name": "MIT",
        "license_category": "permissive",
        "stars": 11800,
        "forks": 2500,
        "watchers": 270,
        "subscribers": 380,
        "created_at": "2011-05-17T10:00:00Z",
        "pushed_at": _e(6),
        "archived": False,
        "is_fork": False,
        "homepage": "https://pytest.org",
        "has_wiki": False,
        "has_pages": False,
        "readme_size_bytes": 16500,
        "topics": ["testing", "python", "unit-testing"],
        "issues": {
            "open_count": 1000,
            "closed_count": 14000,
            "avg_days_open": 65.0,
            "recent_30d_opened": 40,
            "recent_30d_closed": 60,
            "bug_label_count": 320,
        },
        "pull_requests": {
            "open_count": 70,
            "merged_30d": 45,
            "avg_days_to_merge": 10.0,
        },
        "commits": {
            "last_commit_date": _e(5),
            "commits_30d": 130,
            "commits_90d": 420,
            "contributors_90d": 38,
        },
    },
    "jestjs/jest": {
        "source": "github",
        "full_name": "jestjs/jest",
        "url": "https://github.com/jestjs/jest",
        "description": "Delightful JavaScript Testing.",
        "default_branch": "main",
        "language": "TypeScript",
        "license_name": "MIT",
        "license_category": "permissive",
        "stars": 44000,
        "forks": 6600,
        "watchers": 820,
        "subscribers": 1000,
        "created_at": "2014-12-28T10:00:00Z",
        "pushed_at": _e(8),
        "archived": False,
        "is_fork": False,
        "homepage": "https://jestjs.io",
        "has_wiki": False,
        "has_pages": True,
        "readme_size_bytes": 17000,
        "topics": ["testing", "javascript", "unit-testing"],
        "issues": {
            "open_count": 600,
            "closed_count": 10500,
            "avg_days_open": 58.0,
            "recent_30d_opened": 30,
            "recent_30d_closed": 40,
            "bug_label_count": 180,
        },
        "pull_requests": {
            "open_count": 35,
            "merged_30d": 50,
            "avg_days_to_merge": 8.0,
        },
        "commits": {
            "last_commit_date": _e(7),
            "commits_30d": 200,
            "commits_90d": 600,
            "contributors_90d": 55,
        },
    },

    # ── 加解密 / 安全 ──────────────────────────────────────────
    "pyca/cryptography": {
        "source": "github",
        "full_name": "pyca/cryptography",
        "url": "https://github.com/pyca/cryptography",
        "description": "Provides cryptographic recipes and primitives to Python developers.",
        "default_branch": "main",
        "language": "Python",
        "license_name": "Apache-2.0",
        "license_category": "permissive",
        "stars": 6600,
        "forks": 1700,
        "watchers": 210,
        "subscribers": 220,
        "created_at": "2013-09-20T10:00:00Z",
        "pushed_at": _e(9),
        "archived": False,
        "is_fork": False,
        "homepage": "https://cryptography.io",
        "has_wiki": False,
        "has_pages": False,
        "readme_size_bytes": 11000,
        "topics": ["cryptography", "security", "python", "encryption"],
        "issues": {
            "open_count": 48,
            "closed_count": 3600,
            "avg_days_open": 20.0,
            "recent_30d_opened": 12,
            "recent_30d_closed": 20,
            "bug_label_count": 16,
        },
        "pull_requests": {
            "open_count": 6,
            "merged_30d": 22,
            "avg_days_to_merge": 3.0,
        },
        "commits": {
            "last_commit_date": _e(8),
            "commits_30d": 48,
            "commits_90d": 150,
            "contributors_90d": 15,
        },
    },
    "legrandin/pycryptodome": {
        "source": "github",
        "full_name": "Legrandin/pycryptodome",
        "url": "https://github.com/Legrandin/pycryptodome",
        "description": "A self-contained Python package of low-level cryptographic primitives. (PyCrypto successor)",
        "default_branch": "master",
        "language": "Python",
        "license_name": "BSD-2-Clause",
        "license_category": "permissive",
        "stars": 2500,
        "forks": 460,
        "watchers": 62,
        "subscribers": 68,
        "created_at": "2015-05-01T10:00:00Z",
        "pushed_at": _e(90),
        "archived": False,
        "is_fork": False,
        "homepage": "https://www.pycryptodome.org",
        "has_wiki": False,
        "has_pages": False,
        "readme_size_bytes": 7800,
        "topics": ["cryptography", "encryption", "python"],
        "issues": {
            "open_count": 58,
            "closed_count": 760,
            "avg_days_open": 115.0,
            "recent_30d_opened": 2,
            "recent_30d_closed": 4,
            "bug_label_count": 20,
        },
        "pull_requests": {
            "open_count": 2,
            "merged_30d": 1,
            "avg_days_to_merge": 22.0,
        },
        "commits": {
            "last_commit_date": _e(88),
            "commits_30d": 0,
            "commits_90d": 6,
            "contributors_90d": 1,
        },
    },

    # ── 边界测试组件：UNKNOWN_LICENSE ──────────────────────────
    "anon-test/acme-text-utils": {
        "source": "github",
        "full_name": "anon-test/acme-text-utils",
        "url": "https://github.com/anon-test/acme-text-utils",
        "description": "A collection of text utility functions. License file missing.",
        "default_branch": "main",
        "language": "Python",
        "license_name": None,
        "license_category": "unknown",
        "stars": 320,
        "forks": 40,
        "watchers": 12,
        "subscribers": 18,
        "created_at": "2022-01-01T10:00:00Z",
        "pushed_at": _e(45),
        "archived": False,
        "is_fork": False,
        "homepage": None,
        "has_wiki": False,
        "has_pages": False,
        "readme_size_bytes": 2400,
        "topics": ["text", "utils"],
        "issues": {
            "open_count": 8,
            "closed_count": 12,
            "avg_days_open": 60.0,
            "recent_30d_opened": 1,
            "recent_30d_closed": 2,
            "bug_label_count": 3,
        },
        "pull_requests": {
            "open_count": 1,
            "merged_30d": 1,
            "avg_days_to_merge": 15.0,
        },
        "commits": {
            "last_commit_date": _e(40),
            "commits_30d": 6,
            "commits_90d": 18,
            "contributors_90d": 2,
        },
    },

    # ── 边界测试组件：STALE + HIGH_ISSUE_LOAD ──────────────────
    "legacy-tools/python-texttool": {
        "source": "github",
        "full_name": "legacy-tools/python-texttool",
        "url": "https://github.com/legacy-tools/python-texttool",
        "description": "An early 2010s text processing library. Last commit 2022.",
        "default_branch": "master",
        "language": "Python",
        "license_name": "MIT",
        "license_category": "permissive",
        "stars": 890,
        "forks": 160,
        "watchers": 30,
        "subscribers": 30,
        "created_at": "2012-06-01T10:00:00Z",
        "pushed_at": _e(720),
        "archived": False,
        "is_fork": False,
        "homepage": None,
        "has_wiki": True,
        "has_pages": False,
        "readme_size_bytes": 4200,
        "topics": ["text", "legacy"],
        "issues": {
            "open_count": 520,
            "closed_count": 300,
            "avg_days_open": 800.0,
            "recent_30d_opened": 0,
            "recent_30d_closed": 0,
            "bug_label_count": 280,
        },
        "pull_requests": {
            "open_count": 40,
            "merged_30d": 0,
            "avg_days_to_merge": 0.0,
        },
        "commits": {
            "last_commit_date": _e(720),
            "commits_30d": 0,
            "commits_90d": 0,
            "contributors_90d": 0,
        },
    },
}
